Feat database login
Cortes-Maria/Proyecto-HNP pull request #3
Opened 2020-12-09 05:35 UTC by Xfighter32

@yelizondo revise que todo esté bien :)

2020-12-09 05:38 UTC, yelizondo requested changes
Ahí te dejé unos comentarios

2020-12-09 05:38 UTC, yelizondo commented on database/stored-procedures/SP_GetPassword.sql
> +CREATE OR REPLACE PROCEDURE SP_GetPassword (pIdentifier VARCHAR(200), INOUT outPassword VARCHAR(200), INOUT status INT)
Necesito Id y correo

2020-12-09 05:38 UTC, yelizondo commented on database/stored-procedures/SP_CreateUser.sql
> +	pUserType VARCHAR,
Cambiar por el id nada más

2020-12-09 19:42 UTC, Xfighter32 commented on database/stored-procedures/SP_GetPassword.sql
> +CREATE OR REPLACE PROCEDURE SP_GetPassword (pIdentifier VARCHAR(200), INOUT outPassword VARCHAR(200), INOUT status INT)
¿Pero por qué ocupa que le devuelva el correo y el username si es con eso que más bien obtiene la contraseña?

2020-12-09 19:43 UTC, Xfighter32 commented on database/stored-procedures/SP_GetPassword.sql
> +CREATE OR REPLACE PROCEDURE SP_GetPassword (pIdentifier VARCHAR(200), INOUT outPassword VARCHAR(200), INOUT status INT)
Lo del id sí lo entiendo, pero lo otro no

2020-12-09 20:01 UTC, yelizondo commented on database/stored-procedures/SP_GetPassword.sql
> +CREATE OR REPLACE PROCEDURE SP_GetPassword (pIdentifier VARCHAR(200), INOUT outPassword VARCHAR(200), INOUT status INT)
Los uso para crear el token de la sesión, como para que sea un valor más único

2021-01-18 05:29 UTC, yelizondo approved these changes
Looks good

2021-01-18 05:29 UTC, merged